### PR TITLE
Add frontend pagination

### PR DESCRIPTION
**Pull request by garyluu**
For SEAB-2494

Frontend pagination only. Kind of weird numbers I've chosen (9, 18, 36).

https://user-images.githubusercontent.com/24548904/118706504-6bde6f00-b7e7-11eb-95fc-88294fb864b3.mp4

Also feels like I'm missing something

Unrelated: at the end of the video, i show myself clicking in the text field. Does it look weird like that for anyone?

### CODE REVIEW

**Comment by denis-yuen** [comment]
> Does it look weird like that for anyone? 

I think if its the quick highlight/not highllight it doesn't occur for me. But not sure if that's what you meant

**Review by coverbeck — APPROVED** [review]
Those numbers are indeed strange. I do suggest the 10, 25, 50 that we use on search.

**Comment by garyluu** [comment]
> Those numbers are indeed strange. I do suggest the 10, 25, 50 that we use on search.

It's because we mostly display the organizations in columns of three whereas search is a table with 1 result per row

**Comment by garyluu** [comment]
> > Does it look weird like that for anyone?
> 
> I think if its the quick highlight/not highllight it doesn't occur for me. But not sure if that's what you meant

The left side of the highlight is momentarily thinner than the rest

**Comment by denis-yuen** [comment]
Divisible by three makes sense to me. No opinion on exact numbers.

> The left side of the highlight is momentarily thinner than the rest

Oh, then yes. It does.

**Review by denis-yuen — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]

**Pull request merged**
