### PR TITLE
Add new simple confirmation dialog

### PR DESCRIPTION
**Pull request by garyluu**
Adds a simple confirmation dialog.  Use it by subscribing to the service's openDialog() function.  

Remove members confirmation dialog was replaced by  this

### CODE REVIEW

**Comment by garyluu** [comment]
image

**Comment by garyluu** [comment]
> I would also make the close button text optionally user-defined -- I can't think of a specific example right now, but I've seem examples where it might be nice to have more explicit text rather than a generic Cancel.
> 
> Future feature request for really momentous actions: force user to type something as well before Confirm button gets enabled.

Ya, there's a lot of things that can be modified (I mentioned it in the comment).  But since this actually isn't used anywhere right now.  It's best that it's modified when needed.

**Comment by denis-yuen** [comment]
> Ya, there's a lot of things that can be modified (I mentioned it in the method comment). But since this actually isn't used anywhere right now. It's best that it's modified when needed.

Could hook it up with the user self destruct dialogue box to demo how it would actually be used, would kill two birds with one stone

**Comment by garyluu** [comment]
Replaced the member removal dialog with this one.  Had to use innerHTML in order to bold certain things.

**Pull request merged**
