### PR TITLE
Flakey Auth Tests Round Three

### PR DESCRIPTION
**Pull request by Richard-Hansen**
**Description**
This PR re-introduces `cy.waits()` that'd I'd previously removed in: https://github.com/dockstore/dockstore-ui2/pull/1448, because that PR didn't really fix anything... Any suggestions appreciated.

The UI uses javascript to update asynchronously, Cypress is grabbing DOM elements that, after the UI updates, are considered detached, causing tests to fail. After spending a while trying to identify when the UI had updated sufficiently, I was still hitting flakey tests, and succumbed to re-introducing `cy.wait()` at a higher timeout than before.

Hopefully this PR will reduce the flakiness of the auth tests, but it isn't guaranteed. If the auth tests fail again, I'll create a followup ticket to refactor the `my-tools` and `my-workflows` components to see if the flakiness is better addressed from that side. Or, we could reject this PR in favor of that approach in the first place.

**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-1997

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [ ] Check that your code compiles by running `npm run build`
- [ ] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [ ] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [ ] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [ ] Do not use cookies, although this may change in the future
- [ ] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [ ] Do due diligence on new 3rd party libraries, checking for CVEs
- [ ] Don't allow user-uploaded images to be served from the Dockstore domain

### CODE REVIEW

**Comment by coverbeck** [comment]
1. https://filiphric.com/waiting-in-cypress-and-how-to-avoid-it?utm_campaign=Software%2BTesting%2BWeekly&utm_medium=email&utm_source=Software_Testing_Weekly_106 -- "Just use the wait and be done with it" :(.
2. I noticed Cypress is up to 9.x, and there are newer 8.x versions than the 8.0.0 we have installed. Given the above article, it probably won't make a difference, but maybe worth a shot?

**Comment by svonworl** [comment]
I found this open cypress issue, basically a lot of people begging for a fix to our problem:

https://github.com/cypress-io/cypress/issues/7306

No one seems to have a good workaround.

One possibility is to figure out some way to repeat the query if we trigger the "detached DOM" error.  A crude but effective solution might be to create a function called `complete` that would invoke its function argument, catching the error and retrying up to N times, pausing a geometrically-increasing time between retries (to keep the tests running quickly if possible).

You'd use it like:
`complete(() => cy.get('whatever').etc().click());`

Possibly, there's a way to graft it into the cypress system to make it more convenient to use.

**Comment by Richard-Hansen** [comment]
> I found this open cypress issue, basically a lot of people begging for a fix to our problem:
> 
> [cypress-io/cypress#7306](https://github.com/cypress-io/cypress/issues/7306)
> 
> No one seems to have a good workaround.
> 
> One possibility is to figure out some way to repeat the test if we trigger the "detached DOM" error. A crude but effective solution might be to create a function called `complete` that would invoke its function argument, catching the error and retrying up to N times (or until a specified amount of time has elapsed), pausing an initially-small-but-geometrically-increasing amount between retries (to keep the tests running as quickly as possible, but not hog a bunch of cpu).
> 
> You'd use it like: `complete(() => cy.get('whatever').etc().click());`
> 
> Possibly, there's a way to graft it into the cypress system to make it more convenient to use.

I gave this a whirl, but unfortunately it didn't work either. This is because some Cypress requests fail due to a detached DOM, but others get stuck waiting for an element to appear in whatever DOM they are currently looking at, causing an assertion error. I think this is because a detached DOM can cause two separate issues:
1. If we are waiting for an element (that we have located) to reach a certain state, but the DOM is changed, this throws an assertion error, as the element never gets updated. In other words, the test times out
2. We get an element in one request, and then in a subsequent request/chain we interact with it. When we attempt to interact with a detached element, the detached DOM exception is thrown.

In any case though, we have Cypress set to wait 30 seconds for assertions to become true, which takes longer to re-capture the DOM than adding the `cy.wait(8000)`s. Lowering the default Cypress retry may make more tests flakey as well...

Initially, I planned on testing Cypress 9, but the issue linked above has some recent responses that it's still broken :( If we still are interested in Cypress 9, I can create a followup ticket.

For moving forward, I suggest we look to refactoring the UI pages in question to make them more test friendly, as that seems more scalable than trying to hack Cypress to function as desired. But, I'm open for suggestions.

**Comment by svonworl** [comment]
I wonder if, in case #1, we could drastically shorten the wait timeout, catch that error also, and retry similarly?

Or maybe Charles' "just add the waits" is the most pragmatic solution.

**Pull request merged**
