### PR TITLE
Add lambda/plugin version to build info

### PR DESCRIPTION
**Pull request by garyluu**
**Description**
Add the lambda/plugin versions to the copy build info button. It's going to say null for a while no dev until it's set

**Issue**
For SEAB-3517

### CODE REVIEW

**Review by denis-yuen — COMMENTED** [review]
>  Add the lambda/plugin versions to the copy build info button. It's going to say null for a while no dev until it's set 

How about skipping a variable if its null?

**Comment by garyluu** [comment]
> > Add the lambda/plugin versions to the copy build info button. It's going to say null for a while no dev until it's set
> 
> How about skipping a variable if its null?

Considered it, wasn't sure because the other ones say null. While I'm at it, should I skip the other ones too?

**Comment by denis-yuen** [comment]
If I understand correctly, the other variables that show up in the footer are  `webServiceVersion`,  `uiVersion`, `composeSetupVersion`. Kinda hard to deploy without a ui or webservice, but yeah maybe compose setup will be in the same situation eventually as we move more stuff towards cdk

**Comment by garyluu** [comment]
Locally right now (before PR) it's: 
```
[Webservice](https://github.com/dockstore/dockstore/commits/a60e208) - a60e208

[UI](https://github.com/dockstore/dockstore-ui2/commits/9bfa80df) - 2.8.2-87-g9bfa80df

[Compose Setup](https://github.com/dockstore/compose_setup/) - null

[Deploy](https://github.com/dockstore/dockstore-deploy/) - null
```

**Review by denis-yuen — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]

**Review by wshands — APPROVED** [review]

**Pull request merged**
