### PR TITLE
Remove @material-extended/mde

### PR DESCRIPTION
**Pull request by coverbeck**
**Description**
The dependency had an popover we were using in one place -- when clicking on the Share button in the Search page. To remove the dependency, I got rid of the popover, and the Share button now just copies directly to the clipboard.

As discussed in [Slack](https://app.slack.com/archives/C16ET3CF4/p1662679725007619), the other option is to re-implement the popover with Angular/Angular Material, but given that we're only using the component in this one place, which I'm guessing doesn't get a lot of clicks anyway, it doesn't seem worth it to me.

A third option is to change the UI to make it clearer what the Share button is going to do, but I also feel that's overkill. And I'm lazy.

See discussion in [Slack](https://app.slack.com/archives/C16ET3CF4/p1662679725007619), but before, clicking on the share button would bring up the popover:

Screen Shot 2022-09-08 at 4 22 49 PM

Now when clicking on the Share button, it simply displays the `Copied!` snackbar message -- this is the same message UI you get when you click on the copy button in the the intermediate popover.

Screen Shot 2022-09-09 at 9 44 05 AM

**Issue**
dockstore/dockstore#4265

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain

### CODE REVIEW

**Review by denis-yuen — COMMENTED** [review]
is this being affected by https://github.com/dockstore/dockstore/issues/4979 ?

**Comment by denis-yuen** [comment]
(sorry, reviewed too early)

**Comment by coverbeck** [comment]
> is this being affected by [dockstore/dockstore#4979](https://github.com/dockstore/dockstore/issues/4979) ?

Yes, this was that issue. Had to redo the package.json changes in an Ubuntu container, and I think it looks good now.

**Review by denis-yuen — APPROVED** [review]

**Comment by svonworl** [comment]
I like the more spartan interface, but I'm a little concerned that users 
a) won't understand, by dint of its label, what the "Share" button does, and
b) thus won't understand what the "Copied!" snackbar means.

**Comment by kathy-t** [comment]
> I like the more spartan interface, but I'm a little concerned that users a) won't understand, by dint of its label, what the "Share" button does, and b) thus won't understand what the "Copied!" snackbar means.

I agree with Steve. Some ideas:
- I like using the copy button to copy. Maybe we can integrate this somehow?
- Make the share button more descriptive, like "Share search link" or even "Copy search link"

**Comment by denis-yuen** [comment]
Brainstorming: could tooltip and make notification more verbose, like "Copied to clipboard!"

**Comment by coverbeck** [comment]
Various attempts, all using the copy icon instead of the share icon. I think I prefer "Copy search link". Anybody have any strong feelings/preferences?

Also changed "Copied!" to "Copied to clipboard" -- not pushed yet.

Screen Shot 2022-09-12 at 1 21 44 PM
Screen Shot 2022-09-12 at 1 32 37 PM
Screen Shot 2022-09-12 at 1 30 27 PM
Screen Shot 2022-09-12 at 1 26 41 PM
Screen Shot 2022-09-12 at 1 25 46 PM
Screen Shot 2022-09-12 at 1 23 52 PM
Screen Shot 2022-09-12 at 1 23 04 PM

**Comment by denis-yuen** [comment]
Think I like any of 1, 3, 4, 5. So 4 seems fine.

**Comment by coverbeck** [comment]
Went with this one:

Screen Shot 2022-09-13 at 4 01 17 PM

**Review by denis-yuen — APPROVED** [review]

**Review by kathy-t — APPROVED** [review]

**Review by svonworl — APPROVED** [review]

**Pull request merged**
