### PR TITLE
hide the scrollbar on mytools and myworkflows

### PR DESCRIPTION
**Pull request by agduncan94**
Hides the scrollbar on the my entries page since it is ugly, can still scroll.

### CODE REVIEW

**Comment by coverbeck** [comment]
Would it be possible to have before and after screenshots?

**Comment by agduncan94** [comment]
no-scrollbar
scrollbar

**Comment by coverbeck** [comment]
Thanks for the screenshots!

In your no scrollbar screenshot, are there more orgs that are not visible? If so, how do users know they can scroll to view more?

**Comment by agduncan94** [comment]
@coverbeck in the no scrollbar screenshot all of the orgs are shown, none are off screen.

**Pull request merged**
