### PR TITLE
update and add warning for Linux

### PR DESCRIPTION
**Pull request by denis-yuen**
**Description**
Add warning against the use of Docker Desktop with Dockstore CLI

**Review Instructions**
See that the warning appears in the quick-start

**Issue**
https://github.com/dockstore/dockstore/issues/5135

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.

### CODE REVIEW

**Comment by denis-yuen** [comment]
Screenshot from 2022-11-29 18-09-07

**Comment by denis-yuen** [comment]
Think build failure is a false positive

**Comment by aofarrel** [comment]
Do we want to continue telling Mac users to install Docker Desktop? That is what I use without issue, but there's two orange flags here: 
* I'm wondering if some of the Mac permissions weirdness interacts with version of Docker the Mac user has installed. I don't have the bandwidth to investigate this myself.
* [Our docs lead Mac users to Docker Engine instructions but the quick start takes them to a Docker Desktop installer](https://github.com/dockstore/dockstore-documentation/pull/230/files#r1036407213)

**Comment by denis-yuen** [comment]
Hmmm, added an additional comment in the documentation PR, but from https://github.com/dockstore/dockstore/issues/5135 I think I would recommend against Docker Desktop for Linux. I have little experience with Mac, but my understanding is Mac users do not have a choice?

**Comment by coverbeck** [comment]
> Hmmm, added an additional comment in the documentation PR, but from [dockstore/dockstore#5135](https://github.com/dockstore/dockstore/issues/5135) I think I would recommend against Docker Desktop for Linux. I have little experience with Mac, but my understanding is Mac users do not have a choice?

It looks like there are some unofficial workarounds for not installing Docker Desktop on a Mac, but they're not official. So yes, you basically have to install Desktop.

Also, FWIW, my understanding is that the Docker Engine on Mac requires a VM as well... This link is old, but presumably still applicable: https://dev.to/ericnograles/why-is-docker-on-macos-so-much-worse-than-linux-flh

**Review by coverbeck — APPROVED** [review]

**Pull request merged**
