### PR TITLE
SEAB-5545: Add Colab and mybinder.org notebook "launch with" icons

### PR DESCRIPTION
**Pull request by svonworl**
**Description**
This PR adds icons to the notebook "launch with" buttons for Google Colab and mybinder.org.

image

Let's hear it for circles!

The icons are edited SVG versions of:
https://commons.wikimedia.org/wiki/File:Google_Colaboratory_SVG_Logo.svg
https://mybinder.org/static/logo.svg

There is no mybinder.org icon, so the icon is the graphical part of the Binder logo.

I tried to position/kern each so it looked good with respect to the overall layout, as well as the text that follows.

A search for legal/permissions/use information about either icon did not turn up anything.

**Review Instructions**
Go to a notebook entry page on qa, look at the "Launch with" box at upper right, and confirm that the icons appear in the buttons.

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5545

**Security**
If there are any concerns that require extra attention from the security team, highlight them here.

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.
- [x] Check whether this PR disables tests. If it legitimately needs to disable a test, create a new ticket to re-enable it in a specific milestone.

### CODE REVIEW

**Comment by denis-yuen** [comment]
> A search for legal/permissions/use information about either icon did not turn up anything.

In lieu of any other notice, the mybinder logo is here https://github.com/jupyterhub/mybinder.org-deploy/blob/main/mybinder/files/static/badge_logo.svg which seems to imply a BSD-3 license 

Found the google colab icon here https://about.google/brand-resource-center/logos-list/ which means that the rules at https://about.google/brand-resource-center/brand-elements/#product-icons apply

**Review by denis-yuen — APPROVED** [review]
Ok with icons, would like a couple more eyes on the branding guidelines / bsd license

**Review by coverbeck — APPROVED** [review]
Screenshots look nice!

> Ok with icons, would like a couple more eyes on the branding guidelines / bsd license

Agreed with your assessment in other comment; looks good to me legally.

**Review by kathy-t — APPROVED** [review]

**Review by david4096 — APPROVED** [review]

**Review by bvizzier-ucsc — APPROVED** [review]
Looks good to me.
I really like how Google handles their use permissions.

**Pull request merged**
