### PR TITLE
switch to openid connect from access keys in context

### PR DESCRIPTION
**Pull request by denis-yuen**
**Description**

OpenID Connect for ui2 portion of the ticket
Follows https://github.com/dockstore/dockstore-deploy/pull/461
Follows conventions in that PR for back-up of environment variables

Naming is a bit confusing, proposing that we deactivate associated access keys in contexts and verify that nothing is broken over time before deletion

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4284

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain

### CODE REVIEW

**Comment by denis-yuen** [comment]
might be running into the same thing as https://github.com/CircleCI-Public/aws-cli-orb/issues/105

**Comment by denis-yuen** [comment]
confirmed to be fixed in https://github.com/CircleCI-Public/aws-cli-orb/releases 3.1.1

**Review by chmreid — APPROVED** [review]

**Review by kathy-t — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]
> Naming is a bit confusing, proposing that we deactivate associated access keys in contexts and verify that nothing is broken over time before deletion

Probably stating the obvious, but if we do a hotfix for 1.12, we'll either need to cherry-pick this or keep the old context around until we release 1.13.

**Review by david4096 — APPROVED** [review]
Looks good following the improved pattern. Maybe we should make a ticket to finish up the cleanup after a time as you are suggesting.

**Comment by denis-yuen** [comment]
> Looks good following the improved pattern. Maybe we should make a ticket to finish up the cleanup after a time as you are suggesting.

https://ucsc-cgl.atlassian.net/browse/SEAB-4354

**Pull request merged**
