### PR TITLE
Feature/1375/footer cleanup

### PR DESCRIPTION
**Pull request by agduncan94**
Based on comments in https://github.com/ga4gh/dockstore/issues/1375#issuecomment-416624349

screenshot from 2018-08-28 13-51-42

OR

screenshot from 2018-08-28 14-07-22

### CODE REVIEW

**Comment by garyluu** [comment]
Too much empty space imo

**Comment by agduncan94** [comment]
There are two options shown above, comments?

**Comment by denis-yuen** [comment]
Out of the two, I think I prefer the first. 
I do agree that maybe there is too much whitespace so rather than 
```
API                                                      GitHub
UI                                                       Follow Us
Swagger                                                  Gitter
Status
Copyright
```
I was originally thinking 

```
API                                                      Swagger             GitHub
UI                                                       Status              Follow Us
Status                                                   Gitter

Copyright
```

**Comment by agduncan94** [comment]
screenshot from 2018-08-28 14-39-34

**Comment by denis-yuen** [comment]
Let's see. Swagger UI can be just Swagger. 
We can eliminate the empty line/space between the first and second rows. 
The alignment also seems a bit funny. 
(sorry)

**Comment by agduncan94** [comment]
screenshot from 2018-08-28 14-57-24

**Comment by agduncan94** [comment]
I think the alignment issue is with the bottom row mostly. The text is long.

**Pull request merged**
