### PR TITLE
Launch with DNAstack multicloud

### PR DESCRIPTION
**Pull request by kathy-t**
https://github.com/dockstore/dockstore/issues/3197

I'm using a proposed import URL which doesn't work because it's not implemented on the DNAstack side, so the import URL format may change in the future.
- Proposed URL: https://app.dnastack.com/import?trs_server={trs_server}&trs_id={trs_id}&trs_version_id={trs_version_id}&trs_type={trs_type}

Since the DNAstack button shows up with other launch buttons, I changed the other launch buttons to look like the [mock](https://app.zeplin.io/project/5fc690a2717ee9144814f190/screen/60219bda226b07286947fbeb) if the DNAstack multicloud feature is turned on. The appearance is only changed for WDL launch with buttons.

DNAstack multicloud launch

DNAstack multicloud launch menu

Updated galaxy screenshot (since I made the launch with buttons wider):
Galaxy button

### CODE REVIEW

**Comment by coverbeck** [comment]
>     * trs_type={trs_type}

What is trs_type?

**Comment by coverbeck** [comment]
> > ```
> > * trs_type={trs_type}
> > ```
> 
> What is trs_type?

Never mind, from the code I see it is the language.

**Review by coverbeck — APPROVED** [review]
It would be nice if multi-cloud DNAstack and Galaxy button were totally driven off the CloudInstances API. Instead of having a feature flag, which will require a redeploy, you could drive the buttons off what comes back in cloudinstances. If there are no Galaxy instances, don't show the button; if there are any, show it. Then we can control the appearance of the buttons just by invoking the API.

But nice to have, and this seems fine.

**Review by garyluu — APPROVED** [review]
If you don't forsee any styles added to styles.scss used in other parts of the website, move it to the component scss

**Review by denis-yuen — APPROVED** [review]

**Review by dockstoreNameChange — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]
Manage to forget to log back in to my real account every time...

**Pull request merged**
