### PR TITLE
Update OICR logo, remove BW folder by using css

### PR DESCRIPTION
**Pull request by garyluu**
For issue ga4gh/dockstore#1914

Before while hovering over OICR:

image

After while hovering over OICR:

image

Let me know if there's a downside of removing the BW folder.

### CODE REVIEW

**Comment by denis-yuen** [comment]
On the other hand, Nextflow looks a bit big and the bottom is a bit too out-of-place with the other logos?

**Comment by garyluu** [comment]
It's an unrelated change.  My screenshot was production vs my branch (branched from develop)

**Comment by denis-yuen** [comment]
@garyluu @agduncan94  no worries, I think I recall that this was an earlier change too. Nonetheless, could you maybe shrink it a little bit and move it up a tad?

**Comment by garyluu** [comment]
Closing in favor of hotfix branch

**Pull request closed without merging**
