### PR TITLE
Feature/2400/updating tos

### PR DESCRIPTION
**Pull request by Richard-Hansen**
Partner PR: https://github.com/dockstore/dockstore/pull/4035
Wiki docs: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=154540083

Won't pass licensing test, as it is using a different generated file which doesn't contain the updated `TOS_VERSION_2` variable.

### CODE REVIEW

**Review by garyluu — COMMENTED** [review]
Use your webservice branch CircleCI jar for now (just so we can see the tests pass). Change it to develop's CircleCI jar after your webservice PR has been merged.

**Comment by NatalieEO** [comment]
> Use your webservice branch CircleCI jar for now (just so we can see the tests pass). Change it to develop's CircleCI jar after your webservice PR has been merged.

I think the integration tests will fail after this as well. The user should get logged out automatically when they visit the pages. See https://github.com/dockstore/dockstore/pull/2756

**Comment by Richard-Hansen** [comment]
> > Use your webservice branch CircleCI jar for now (just so we can see the tests pass). Change it to develop's CircleCI jar after your webservice PR has been merged.
> 
> I think the integration tests will fail after this as well. The user should get logged out automatically when they visit the pages. See [dockstore/dockstore#2756](https://github.com/dockstore/dockstore/pull/2756)

Yeah, the UI will loop you into a 'session expired' page when the TOS is outdated. I'll change the jar.

**Review by coverbeck — COMMENTED** [review]
See my question about privacy policy in your web service PR. This may be fine as is, but would like to be sure.

**Comment by denis-yuen** [comment]
Don't have time for a full review, but can we get this to a hotfix branch?
Think there is chance we will need this sooner rather than later if 1.11 drags

**Comment by Richard-Hansen** [comment]
Moving to another PR.

**Pull request closed without merging**
