### PR TITLE
Add userAgent to cypress.json (SEAB-4202)

### PR DESCRIPTION
**Pull request by amarjandu**
**Description**
Use unique userAgent in cypress config to enable filtering usage analytics in Google.

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4202

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain

### CODE REVIEW

**Comment by amarjandu** [comment]
Unable to confirm that the user agent is showing in Google Analytics, looked under the left-toolbar `Reports -> Technology -> Browser & OS`.

It might be because integration-tests do not use `dockstore-dev` for testing.

**Comment by denis-yuen** [comment]
> Unable to confirm that the user agent is showing in Google Analytics, looked under the left-toolbar `Reports -> Technology -> Browser & OS`.
> 
> It might be because integration-tests do not use `dockstore-dev` for testing.

The UI tests do spin up their own database and webservice. It's possible that we they never make it out to our sites at all unlike our webservice/CLI tests which are leaky

**Comment by Richard-Hansen** [comment]
> Unable to confirm that the user agent is showing in Google Analytics, looked under the left-toolbar `Reports -> Technology -> Browser & OS`.
> 
> It might be because integration-tests do not use `dockstore-dev` for testing.

We have smoke tests that run against the deployed dev/staging/prod stages. If you use the CircleCI config in this PR and run `npm run test-dev-no-auth` (This runs Cypress tests, you may need to remove `--reporter junit` if not setup locally, see https://github.com/dockstore/dockstore-ui2/blob/77679781a26213565cca03b4f729c2adb1d6f07a/package.json#L33) locally, that should show up in google analytics.

**Review by Richard-Hansen — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]

**Comment by amarjandu** [comment]
> you may need to remove `--recorder` if not setup locally

I ended up removing `--record` and confirmed the new User Agent in the dashboard! Thanks! @Richard-Hansen

**Review by denis-yuen — APPROVED** [review]

**Pull request merged**
