### PR TITLE
The not-beta label

### PR DESCRIPTION
**Pull request by garyluu**
Outdated images removed
https://github.com/dockstore/dockstore/issues/3083

### CODE REVIEW

**Comment by denis-yuen** [comment]
Vote on Slack, +2,+1,-1,-2 options

**Comment by garyluu** [comment]
image

image

**Comment by garyluu** [comment]
image
image
image

**Comment by coverbeck** [comment]
Could you round the corners, or was that voted down in the poll?

**Comment by garyluu** [comment]
> Could you round the corners, or was that voted down in the poll?

I think that was voted down.  The people have spoken.

**Pull request merged**
