### PR TITLE
Update Mac OS OpenJDK instructions

### PR DESCRIPTION
**Pull request by aofarrel**
**Description**
Updates Mac OS installation instructions for OpenJDK to account for:
* Newer versions of Mac OS now being cagey about stuff from "unidentified developers"
* Newer versions of Mac OS defaulting to zsh, not bash

I don't know exactly what version of Mac OS these changes were made, but it was several major versions ago. The zsh default for instance is 10.15 Catalina, which came out 2019.

**Review Instructions**
* I did not actually test this compiles yet 🙃 
* We're still telling people to install OpenJDK 11 for Mac but 17 for Linux, and have version 17 show in the output of step 4. Ideally these should be consistent.

**Issue**
N/A - was going through the steps myself on some new hardware, had some issues, started writing a ticket, then realized I could fix it myself.

**Security**
N/A beyond the usual concerns about older JDKs.

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [ ] Check that your code compiles by running `npm run build`
- [ ] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [ ] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [ ] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [ ] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain
- [ ] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.
- [ ] Check whether this PR disables tests. If it legitimately needs to disable a test, create a new ticket to re-enable it in a specific milestone.

### CODE REVIEW

**Comment by aofarrel** [comment]
This is the sort of issue you end up with when the "unidentified developer" thing isn't dealt with:

```
>which java                                                           
/usr/bin/java

>echo $JAVA_HOME                                                       
/usr/bin/java

>java -version                                                      
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```

**Comment by denis-yuen** [comment]
> Newer versions of Mac OS now being cagey about stuff from "unidentified developers"

:question:

**Comment by aofarrel** [comment]
> > Newer versions of Mac OS now being cagey about stuff from "unidentified developers"
> 
> ❓

https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

Yes, OpenJDK 11 is considered being from an unidentified developer -- likely because it predates Apple's system.

**Comment by aofarrel** [comment]
The lint_license_unit_test_coverage failure kind of looks like a credential issue? Will investigate after checking JDK 17 works + this PR doesn't break anything.

**Comment by denis-yuen** [comment]
> Yes, OpenJDK 11 is considered being from an unidentified developer -- likely because it predates Apple's system.

Weird, but ok. 

Tagging @coverbeck or @svonworl maybe they'd know if Java 17 is in this system.

**Comment by coverbeck** [comment]
> We're still telling people to install OpenJDK 11 for Mac but 17 for Linux

Yikes, The 1.14 CLI requires Java 17, and it looks like we only updated the Linux instructions, not the Mac instructions. It's not only a consistency issue, the 1.14 CLI shouldn't work at all with Java 11. Thanks for noticing.

Pretty sure the build issue is because you're building from a fork -- forks don't have access to the SonarCloud token nor other secrets.

**Comment by aofarrel** [comment]
> Pretty sure the build issue is because you're building from a fork -- forks don't have access to the SonarCloud token nor other secrets.

Figured as much. GitHub claims I don't have the requisite permissions to make a not-fork branch, so someone might need to cherrypick these commits to a not-fork branch to get that part to pass. I'll mark this PR as "ready to review" when ready for that to happen.

**Pull request closed without merging**
