### PR TITLE
Release 2.9 clone

### PR DESCRIPTION
**Pull request by denis-yuen**
**Description**
What-if attempting the update on GitHub
Update  from release branch (centre balloon)
https://datasift.github.io/gitflow/GitFlowMasterBranch.png

In particular, I'm not sure if I merged properly for the following, watch out for a screwed up merge conflict in:

Screenshot from 2022-03-15 17-07-16
:grimacing: 

- ui redesign buttons by @KimberleyChong 
- gravatar fix by @svonworl 

You primarily just want to focus on the merge commit

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4050

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4050

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [ ] Check that your code compiles by running `npm run build`
- [ ] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [ ] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [ ] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [ ] Do not use cookies, although this may change in the future
- [ ] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [ ] Do due diligence on new 3rd party libraries, checking for CVEs
- [ ] Don't allow user-uploaded images to be served from the Dockstore domain

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]
Gravatar and App Tools table changes look good to me.

Going to add @Richard-Hansen since he did the launch page changes.

**Comment by svonworl** [comment]
We don't need https://github.com/dockstore/dockstore-ui2/pull/1490/commits/740e260635a4c4db164229f01ed5d2a5c969a2b9, the file changed by that commit (src/app/search/basic-search/basic-search.component.html) was correct beforehand, I think.

**Comment by denis-yuen** [comment]
> We don't need [740e260](https://github.com/dockstore/dockstore-ui2/commit/740e260635a4c4db164229f01ed5d2a5c969a2b9), the file changed by that commit (src/app/search/basic-search/basic-search.component.html) was correct beforehand, I think.

breaks the tests though

**Review by Richard-Hansen — APPROVED** [review]
WES launch tab looks good.

**Review by kathy-t — APPROVED** [review]

**Pull request merged**
