### PR TITLE
Clarify message

### PR DESCRIPTION
**Pull request by garyluu**
For dockstore/dockstore#2663

If you're wondering why CircleCI didn't run...I have no idea either

### CODE REVIEW

**Comment by denis-yuen** [comment]
It's not clear to me (maybe a screenshot would be in order) what this would look like. 
Also, is this a warning message that would appear only when the Google token is expired or all the time?

**Comment by coverbeck** [comment]
> It's not clear to me (maybe a screenshot would be in order) what this would look like.
> Also, is this a warning message that would appear only when the Google token is expired or all the time?

It would be nice if we could display the message only when the refresh token has expired, in response to a failed Ajax call. The problem is that I don't think the Dockstore API easily lets us glean this information.

How about setting a flag in the call to `getWorkflowPermissions` if the response is 401 (or 403), and only displaying this then?

**Comment by denis-yuen** [comment]
> How about setting a flag in the call to `getWorkflowPermissions` if the response is 401 (or 403), and only displaying this then?

That sounds good for now, maybe in a later release we can check on the status of tokens before displaying them in the linked accounts page.

**Comment by garyluu** [comment]
> It's not clear to me (maybe a screenshot would be in order) what this would look like.
> Also, is this a warning message that would appear only when the Google token is expired or all the time?

It's displayed when the getWorkflowPermissions endpoint has not returned a valid response.

**Comment by garyluu** [comment]
image

**Comment by garyluu** [comment]
Basically, if you have a Google account and for whatever reason, permissions cannot be gotten (either due to Terra not being linked or Google refresh token expired), this message will show

**Pull request merged**
