### PR TITLE
Seab 1632/tool tester logs smoke test

### PR DESCRIPTION
**Pull request by NatalieEO**
https://ucsc-cgl.atlassian.net/browse/SEAB-1632

### CODE REVIEW

**Review by coverbeck — COMMENTED** [review]
Does this only work on prod? I'm pretty sure it doesn't work on dev, and may not have been configured for staging....

If so, it needs to come out of basic-enduser.ts, and the smoke tests in package.json for prod (and staging?) should include an additional file.

**Comment by NatalieEO** [comment]
> Does this only work on prod? I'm pretty sure it doesn't work on dev, and may not have been configured for staging....
> 
> If so, it needs to come out of basic-enduser.ts, and the smoke tests in package.json for prod (and staging?) should include an additional file.

checked and the logs table only exists in production right now

**Comment by denis-yuen** [comment]
> checked and the logs table only exists in production right now 

The webservice reads content from a S3 bucket for that I believe. 
Maybe we should have another S3 bucket for staging or point staging at the prod bucket (there are no secrets there)

**Comment by denis-yuen** [comment]
> Does this only work on prod? I'm pretty sure it doesn't work on dev, and may not have been configured for staging....
> 
> If so, it needs to come out of basic-enduser.ts, and the smoke tests in package.json for prod (and staging?) should include an additional file.

Didn't see this, but this probably covers it

**Review by coverbeck — APPROVED** [review]

**Review by garyluu — APPROVED** [review]

**Pull request merged**
