### PR TITLE
SEAB-3091:  update akita to 8.0.1 and akita-ngdevtools to 7.0.0

### PR DESCRIPTION
**Pull request by hyunnaye**
**Description**
This PR updates akita and akita-ngdevtools to their latest versions, 8.0.1 and 7.0.0 respectively

**Review Instructions**
QA should function properly.

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-3091

**Security**
If there are any concerns that require extra attention from the security team, highlight them here.

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.
- [x] Check whether this PR disables tests. If it legitimately needs to disable a test, create a new ticket to re-enable it in a specific milestone.

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]
Ah cool, I was worried that an upgrade to a major version would break things.

Should this be targetting the release branch instead of develop?

**Comment by denis-yuen** [comment]
> Should this be targetting the release branch instead of develop?

Ah right, yes

**Comment by hyunnaye** [comment]
> Ah cool, I was worried that an upgrade to a major version would break things.
> 
> Should this be targetting the release branch instead of develop?

Thanks for catching that. Changed base to the release branch :)

**Review by kathy-t — APPROVED** [review]
Not sure, do we need to revert the previous PR since that didn't fix the snyk warning? https://github.com/dockstore/dockstore-ui2/pull/1873

**Pull request merged**
