### PR TITLE
Feature/2073/seperate tools and workflows tab

### PR DESCRIPTION
**Pull request by nrzhao4**
- for part of [SEAB-2073](https://ucsc-cgl.atlassian.net/browse/SEAB-2073)
- implemented some of the [new UI](https://projects.invisionapp.com/share/VNZ92Z0T2B3#/screens/436191418)
- sidebar facets are now independent for workflows and tabs, only applies to current tab
- searching the in the search bar returns results only from the current tab
- clicking a different tab resets all search terms and filters
- to make tabs above sidebar and results table, moved the mat-tab from `search-results.component` to `search.component`
- updated icons and text colour in tab labels
Screen Shot 2020-12-23 at 3 00 48 PM
Screen Shot 2020-12-23 at 3 00 35 PM

### CODE REVIEW

**Review by coverbeck — COMMENTED** [review]
Initial comment from running branch locally -- there is a message that says it is only showing 100 results, but it's showing more than 200. See screenshot.

Also, it was already like this, but I just noticed it now, when you first go to the search page, it limits the number of results it displays, but there's no message saying it's only displaying some of the entries. Then when you click a facet, the message appears that it's only displaying some of the entries. I was confused by this. I should write this one up separately, but wait until this one gets merged.

Screen Shot 2020-12-23 at 2 33 25 PM

**Comment by coverbeck** [comment]
Ran this locally and seems to be working fine. But:

1. My last comment was not addressed
2. There's a merge conflict that somebody will have to resolve.

**Comment by garyluu** [comment]
Fixed the conflict...i hope

**Comment by denis-yuen** [comment]
> Also, it was already like this, but I just noticed it now, when you first go to the search page, it limits the number of results it displays, but there's no message saying it's only displaying some of the entries. Then when you click a facet, the message appears that it's only displaying some of the entries. I was confused by this. I should write this one up separately, but wait until this one gets merged. 

I think this was intentional.

**Review by NatalieEO — APPROVED** [review]

**Comment by garyluu** [comment]
Notes (mostly for myself):
- Many minor changes that I already implemented
- Main issue is that the original dev page has 6 queries


 * There are a total of 6 calls per search in dev.
 * 2 calls are from the tag cloud (1 for tool, 1 for workflow)
 * 1 calls are for the sidebar bucket count
 * 1 call for the autocomplete
 * 2 calls for the actual results (1 for tool, 1 for workflow)
 
 prod has 7 calls, don't know why
 
 This PR has 7 calls + 2 calls when switch from tools to workflows.

Ideally, initial load (workflow) should have 3 + 2 "cached" calls:
1 call for sidebar bucket count, 1 call for autocomplete, 1 call for actual results.  2 calls for both the tool and workflow tag clouds.
switching to tools should also be the same calls

**Review by coverbeck — APPROVED** [review]

**Review by denis-yuen — APPROVED** [review]

**Comment by garyluu** [comment]
Re-requesting reviews for my changes

**Review by dockstoreNameChange2 — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]
Lol oops, I was testing things on another dummy account for a ticket I have.

**Review by coverbeck — APPROVED** [review]

**Pull request merged**
