### PR TITLE
Show all versions

### PR DESCRIPTION
**Pull request by garyluu**
Showing all versions instead of just the ones on the sidebar.

Tried altering the sortVersions function to show more than 5, but the table sorting will overwrite it regardless.

### CODE REVIEW

**Comment by denis-yuen** [comment]
How is the order of versions in the drop-down vs the order in the versions table with this change?

**Comment by agduncan94** [comment]
I think they should be the same order since they are both directly looking at workflow.workflowVersions or tool.tags

**Comment by garyluu** [comment]
So this change basically reverts it back to how it is on production.  It looks the the versions table will by default sort the versions by name (overwriting any sorting that was done previously).  The versions in the dropdown however somehow manages to sort by date (which doesn't look like the order returned by webservice)

**Comment by garyluu** [comment]
Just to double check, you want the dropdown to match the order of the versions table?  i.e. sorting the dropdown by name by default.  then if the versions table is changed to sort by date modified, the dropdown will also be sorted by date modified?

**Comment by denis-yuen** [comment]
I don't think they need to maintain sort order if the user sorts.
However, I do expect the two to be in sync when I first land on the page.
Out of the two sorts (sort by name, sort by date modified), I think sort by date modified is probably better assuming latest first.

**Comment by garyluu** [comment]
ok, should be much easier than syncing the sort then

**Pull request merged**
