### PR TITLE
git secrets fix

### PR DESCRIPTION
**Pull request by Richard-Hansen**
**Description**
Git secrets was failing locally to catch failed patterns within our test databases. Interestingly, I had setup and installed git-secrets manually using `brew`. This failed to capture the sql database secret warnings, but would catch fake keys, such as `AKIAIOSFODNN7EXAMPLES`, which led me to believe that it was working as expected.

Uninstalling locally with `brew uninstall git-secrets` and then reinstalling using the UI script `npm run install-git-secrets` seemed to fix the local issue, and caused `git secrets --scan` to start picking up the expected results.

If you aren't sure if git secrets is working locally, I'd suggest scanning one of the database files, such as `test/smoke_test_db.sql` while the line  `test/smoke_test_db.sql:.*public.databasechangelog` isn't in `.gitallowed`. If your scan passes, git secrets may be broken.

**Issue**
A link to a github issue or SEAB- ticket (using that as a prefix)

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [ ] Check that your code compiles by running `npm run build`
- [ ] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [ ] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [ ] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [ ] Do not use cookies, although this may change in the future
- [ ] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [ ] Do due diligence on new 3rd party libraries, checking for CVEs
- [ ] Don't allow user-uploaded images to be served from the Dockstore domain

### CODE REVIEW

**Review by coverbeck — COMMENTED** [review]
I'm confused, if I run `npm run install-git-secrets.sh` off the release/2.9 branch, I get a bunch of errors:

```
~/git/dockstore/dockstore-ui2$ npm run install-git-secrets

> dockstore-ui2@2.8.0 install-git-secrets /Users/charlesoverbeck/git/dockstore/dockstore-ui2
> ./scripts/install-git-secrets.sh

+ which git-secrets
+ echo 'git secrets is already installed'
git secrets is already installed
+ which git-secrets
+ git secrets --register-aws
+ git secrets --add '[a-fA-F0-9]{30,}'
+ true
+ git secrets --scan
.circleci/config.yml:131:              wget -O scripts/npm-audit.sh https://raw.githubusercontent.com/dockstore/dockstore-ui2/4b885b51c3fdc1b0faa6450c20e919587bb3f665/scripts/npm-audit.sh
.circleci/config.yml:132:              wget -O scripts/compare-num-vulns.sh https://raw.githubusercontent.com/dockstore/dockstore-ui2/4b885b51c3fdc1b0faa6450c20e919587bb3f665/scripts/compare-num-vulns.sh
test/github_app_tool_db_dump.sql:180:INSERT INTO public.workflowversion (id, lastmodified, reference, valid, workflowpath, name, dirtybit, dbcreatedate, dbupdatedate, referencetype, versioneditor_id, commitid, subclass, frozen, parentid, islegacyversion, dagjson, tooltablejson, synced) VALUES (30, '2022-01-12 14:48:20.000000', 'test', true, '/tools/Dockstore.cwl', 'test', false, '2022-01-12 14:51:23.668000', '2022-01-12 14:51:23.691000', 'BRANCH', null, '31fe36add1e3f613b649a99196e519d459b610b2', null, false, 50, false, null, null, true);
test/github_app_tool_db_dump.sql:181:INSERT INTO public.workflowversion (id, lastmodified, reference, valid, workflowpath, name, dirtybit, dbcreatedate, dbupdatedate, referencetype, versioneditor_id, commitid, subclass, frozen, parentid, islegacyversion, dagjson, tooltablejson, synced) VALUES (31, '2022-01-12 14:45:20.000000', 'main', true, '/tools/Dockstore.cwl', 'main', false, '2022-01-12 14:45:55.386000', '2022-01-12 14:45:55.576000', 'BRANCH', null, 'a7bb91d678d5cb9c973289db6c962a6a238186ea', null, false, 51, false, null, null, true);

<a bunch of stuff truncated>
```

I'm unclear why it's not working for you but is working for me, and why you need to add that change.

**Comment by coverbeck** [comment]
> `npm run install-git-secrets` works for me, as in it correctly flags the DB dumps. My previous setup didn't flag the DBs (which was manually downloading with `brew install git-secrets` and a subsequent `git secrets --install`). I'm not sure why this is the case, but the two SQL database dumps should have been added to `.gitallowed` when they were initially commit, but they seem to have skated by unseen. This PR adds them to `.gitallowed` so `git secrets --scan` no longer reports them, as they are false positives.
> 
> It seems our CI scanning may not be catching git secrets issues, similar to the local issue that I had? Not certain, I think @garyluu was taking a look?

Ah, I see. I think the idea is to scan new commits, not scour the past for existing secrets.

If I'm understanding right, I don't think you should do this PR. If you add a new token to the test database, we would want it scanned and you would need to explicitly approve/ignore it. ideally and probably always you will add a fake secret, but you could accidentally add a real secret, and the hook should force you to double check.

**Comment by garyluu** [comment]
I noticed we had secrets issues because I was making unrelated commits and somehow git secrets complained about the two files and wouldn't let me commit

**Comment by Richard-Hansen** [comment]
> I noticed we had secrets issues because I was making unrelated commits and somehow git secrets complained about the two files and wouldn't let me commit

If I'm understanding this correctly, we have two main ways we can implement git secrets:
1. Only scan new commits
2. Scan the entire commit tree

And we have local installments of git secrets that behave differently:
1. Some only scan new file changes
2. Some scan the entire commit tree

No strong opinions from me, I think both approaches are reasonable, but is there a purpose to `.gitallowed` if we are only scanning the latest changes? If a new change is caught by git secrets, you'd presumably skip verification for the offending commit and it would never be scanned again (unless modified somewhere down the line), correct?

**Review by garyluu — APPROVED** [review]
ideally, the CI should also scan for secrets since it's apparent that relying on the developers to have git secrets working is not 100% reliable.

**Comment by Richard-Hansen** [comment]
Going to close this PR and suggest we keep the current `git-secrets` functionality pattern. Feel free to reopen if anyone disagrees.

**Pull request closed without merging**
