### PR TITLE
Deal with Firefox copy-and-paste annoyance

### PR DESCRIPTION
**Pull request by denis-yuen**
Working on https://github.com/ga4gh/dockstore/issues/1622

### CODE REVIEW

**Comment by garyluu** [comment]
Token starts disappearing at roughly col-md size

**Comment by denis-yuen** [comment]
Hmmm, rats. Need a way of getting it to display properly at small screen sizes but not automatically break on Firefox vs Chrome.

**Comment by denis-yuen** [comment]
(feel free to clean-up either here or separately)

**Comment by garyluu** [comment]
class="small" might've worked too

**Pull request merged**
