### PR TITLE
Set user to be initially undefined

### PR DESCRIPTION
**Pull request by garyluu**
So the problem is...

Initially user is null (logged out home page appears)
User is gotten by webservice (logged out home page still shown)
Then user gets set (logged in home page appears)

Changed it so that `user` is initially undefined. This is interesting because async piping in an ngIfElse statement appears to cause neither branches to execute. So in this fix, nothing appears until user is set (either null or actually something). 

End result is it's only set once and logged in homepage or logged out homepage only appears once.

Kind of a dangerous change, leaving out of 1.8.0.

For https://github.com/dockstore/dockstore/issues/3151

### CODE REVIEW

**Comment by agduncan94** [comment]
@garyluu does this solve https://github.com/dockstore/dockstore/issues/3121 point 6?

**Comment by garyluu** [comment]
It does, the other way would be to use the loading thing instead (which would probably be less disruptive)

**Comment by coverbeck** [comment]
This is fixing dockstore/dockstore#3121, point 6, right? But that ticket is marked as closed. Confused...

**Review by denis-yuen — APPROVED** [review]
Seems worth a try in 1.11

**Comment by garyluu** [comment]
> This is fixing [dockstore/dockstore#3121](https://github.com/dockstore/dockstore/issues/3121), point 6, right? But that ticket is marked as closed. Confused...

Oh ya, I guess there was a ticket for this after all.

**Review by NatalieEO — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]
Still a little confused why we need this if the related issue has already been fixed, but we can try it and see.

**Comment by garyluu** [comment]
> Still a little confused why we need this if the related issue has already been fixed, but we can try it and see.

It has not been fixed. notice how the last checkbox was not checked off

**Pull request merged**
