### PR TITLE
Feature/2969/gi logo

### PR DESCRIPTION
**Pull request by emlys**
dockstore/dockstore#2969
Replaced UCSC sponsor logo with GI one

### CODE REVIEW

**Comment by emlys** [comment]
Used a logo from here https://ucscgenomics.soe.ucsc.edu/media-resources/ instead of the one in the ticket so it would be colored when you hover over it like the others

**Comment by emlys** [comment]
It's hard to tell if it's aligned correctly or not since all the logos are different shapes. Let me know if it looks off to you

**Comment by coverbeck** [comment]
Please attach screenshot.

**Comment by emlys** [comment]
Screen Shot 2019-11-15 at 11 27 15 AM

**Pull request merged**
