### PR TITLE
add git secrets checks

### PR DESCRIPTION
**Pull request by wshands**
Addresses https://ucsc-cgl.atlassian.net/browse/SEAB-1517

### CODE REVIEW

**Comment by wshands** [comment]
David, @david4096 I know you said we don't need to automatically instal git secrets but maybe it is a good idea to do that so the user doesn't have to do it? If so I suppose a shell script could be added and called from package.json scripts prebuild?

**Comment by david4096** [comment]
@wshands I like this idea. It's probably not too hard to write a shell script that detects the two environments we run under, checks for `git secrets` on the path, and installs either via homebrew or directly via make if its not detected. That same script would be present at other repos to check for whether `git secrets` is on the path so it's probably reusable. The objection in general is people avoid mucking with system requirements and leave that up to the developer since it can cause other problems. git secrets is simple and stable enough I'm not too worried about it.

At dockstore-java git secrets is installed in the CI, so you can take the changes made there to perform the install part of the script for linux, at least. I think mac people prefer to use homebrew to manage source installs and I think this script would also have to test for the presence of `brew`.

**Comment by wshands** [comment]
Added git secrets install script

**Comment by garyluu** [comment]
> Added git secrets install script but it should be run from "prebuild"?

No, I would not want to install gitsecrets every time i build

**Review by denis-yuen — APPROVED** [review]

**Review by garyluu — APPROVED** [review]

**Review by david4096 — APPROVED** [review]
Great, I tested the install script and it worked as expected on linux/ubuntu.

I also tested that a credentials file could not be added to a commit.

It should be pretty easy to add this to CI so that builds that includes secrets will fail. @Ldcabansay is this install script useful to you?

**Comment by Ldcabansay** [comment]
> Great, I tested the install script and it worked as expected on linux/ubuntu.
> 
> I also tested that a credentials file could not be added to a commit.
> 
> It should be pretty easy to add this to CI so that builds that includes secrets will fail. @Ldcabansay is this install script useful to you?

Yeah I'm using the same, working on the CI part

**Review by coverbeck — APPROVED** [review]
The minimal is to run git-secrets in the pre-commit. And just fail if the user didn't install git-secrets. I would have been ok with that.

But since you wrote the script to actually install, you could go ahead with the CI job as David suggests. I think it's somewhat useful in that if we had to remove a credential from a branch, at least it wouldn't be in the main branch, but even so, it would be a little too late.

**Pull request merged**
