### PR TITLE
Update Circle artifacts, old ones had expired

### PR DESCRIPTION
**Pull request by coverbeck**
**Description**
Update Circle artifacts, old ones had expired.

Remove circle_ci_source, which isn't used and was
confusing me; I had kept updating it, and it didn't fix
anything. :)

**Issue**
None

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain

### CODE REVIEW

**Review by david4096 — APPROVED** [review]

**Review by svonworl — APPROVED** [review]

**Comment by coverbeck** [comment]
Grr, local_smoke_tests keep failing.

I noticed that the last [successful](https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2/8156/workflows/a2b9cf8e-70a2-4416-bf19-92564ddc401a/jobs/30754/parallel-runs/0/steps/0-115) local_smoke_tests index 13 entries; the latest [failure](https://app.circleci.com/pipelines/github/dockstore/dockstore-ui2/8166/workflows/98256ac0-28cd-4028-aa6d-a7c21ddc6d86/jobs/30795/parallel-runs/0/steps/0-115) only indexed 0 entries. All failures I've looked at seem to have indexed 0 entries, actually.

**Review by denis-yuen — COMMENTED** [review]
seems in progress, turns off all integration tests and deletes the package-lock file?

**Comment by denis-yuen** [comment]
Seeing what is going on, ignoring what is going on with the license file 
https://github.com/dockstore/dockstore-ui2/pull/1581

**Comment by coverbeck** [comment]
> seems in progress, turns off all integration tests and deletes the package-lock file?

Sorry, I should have un-requested reviews. It seemed a straightforward PR when I first did it, but then the smoke tests failed, so I tried to narrow it down.

**Comment by kathy-t** [comment]
> Remove circle_ci_source, which isn't used and was confusing me; I had kept updating it, and it didn't fix anything. :)

I think that's meant to be a helpful link to track down which circle ci job the artifacts came from and to see if they expired (at least that's how I use it :slightly_smiling_face:)

**Review by david4096 — APPROVED** [review]

**Comment by coverbeck** [comment]
> > Remove circle_ci_source, which isn't used and was confusing me; I had kept updating it, and it didn't fix anything. :)
> 
> I think that's meant to be a helpful link to track down which circle ci job the artifacts came from and to see if they expired (at least that's how I use it 🙂)

Interesting; it had been a while since I had update the artifacts; I'd forgotten you'd added the `circle_build_id`, and went through a few iterations of updating the `circle_ci_source` and it still not working, and got confused. :)

Can't you just go to https://app.circleci.com/pipelines/github/dockstore/dockstore/`circle_build_id`?

The thing I don't like about editing that line is that you can't just copy the link in the CircleCI; you have to manually edit the url:

Copied link: https://output.circle-artifacts.com/output/job/07e87717-3dd8-4830-a053-60bd746ab898/artifacts/0/tmp/artifacts/openapi.yaml

Link in package.json: https://app.circleci.com/pipelines/github/dockstore/dockstore/8054/workflows/a8b4f969-3415-4457-b198-826af9564417/jobs/21610/artifacts

Different subdomain, etc., so then I have to manually edit it. Unless I'm doing it wrong?

**Comment by kathy-t** [comment]
> Can't you just go to [https://app.circleci.com/pipelines/github/dockstore/dockstore/`circle_build_id`](https://app.circleci.com/pipelines/github/dockstore/dockstore/%60circle_build_id%60)?

Hmm, I don't believe that works. I tried with your updated build id and it was a 404

> The thing I don't like about editing that line is that you can't just copy the link in the CircleCI; you have to manually edit the url:
> 
> Copied link: https://output.circle-artifacts.com/output/job/07e87717-3dd8-4830-a053-60bd746ab898/artifacts/0/tmp/artifacts/openapi.yaml
> 
> Link in package.json: https://app.circleci.com/pipelines/github/dockstore/dockstore/8054/workflows/a8b4f969-3415-4457-b198-826af9564417/jobs/21610/artifacts
> 
> Different subdomain, etc., so then I have to manually edit it. Unless I'm doing it wrong?

You don't need to manually edit it. The link is for the artifacts tab of your CircleCI build (like this [one](https://app.circleci.com/pipelines/github/dockstore/dockstore/8306/workflows/e18ef287-6356-4e52-b412-01de0d2a3622/jobs/22808/artifacts)), not the link to the actual artifact itself. I like to refer to this wiki when I need a refresher :slightly_smiling_face:  https://wiki.oicr.on.ca/display/DOC/Use+CircleCI+Backend+Artifacts+in+the+Frontend

**Comment by coverbeck** [comment]
> You don't need to manually edit it. The link is for the artifacts tab of your CircleCI build (like this [one](https://app.circleci.com/pipelines/github/dockstore/dockstore/8306/workflows/e18ef287-6356-4e52-b412-01de0d2a3622/jobs/22808/artifacts)), not the link to the actual artifact itself. I like to refer to this wiki when I need a refresher 🙂 https://wiki.oicr.on.ca/display/DOC/Use+CircleCI+Backend+Artifacts+in+the+Frontend

Ah, OK, thanks for clarifying. I'll restore it if I can get the build working. :)

**Comment by coverbeck** [comment]
Closing in favor of #1581

**Pull request closed without merging**
