### PR TITLE
add text to funding page and update ontario logo

### PR DESCRIPTION
**Pull request by Ldcabansay**
https://github.com/dockstore/dockstore/issues/2493
https://github.com/dockstore/dockstore/issues/2465
Adds text to funding page and updates Ontario logo. Also adds BISTI and STAGE funding info

### CODE REVIEW

**Comment by Ldcabansay** [comment]
image

image

Btw that extra sized gap before the datastage panel isn't really there, that's just the result of two screenshots.

**Comment by coverbeck** [comment]
When referring to an issue, you need to preface with dockstore/dockstore, because the issues are in a different repo. It would also be good if those issues got into the commit message when you merge.

**Comment by coverbeck** [comment]
In the wording for DataSTAGE, it says "...to create a community of practice...". Should that be "practices"? If it came from them like that, never mind.

**Comment by denis-yuen** [comment]
> When referring to an issue, you need to preface with dockstore/dockstore, because the issues are in a different repo. It would also be good if those issues got into the commit message when you merge.

You can also copy-paste the whole URL if that happens to be easier

**Pull request merged**
