### PR TITLE
DOCK-2105: Render newlines in GitHub app log messages

### PR DESCRIPTION
**Pull request by svonworl**
**Description**
This PR changes the UI so that newlines in the github apps log messages are formatted as newlines, rather than whitespace.  The log message style is changed so it preserves whitespace and is rendered in a small, monospace font, with a tighter-than-usual line height to fit more output in the available space.  The formatting is similar to how the message might look if it was within a `<pre>` tag.

Screen Shot 2022-05-04 at 5 31 28 PM

These changes will improve the readability of multiline messages, and preserve the formatting of useful, preformatted messages, such as [some of] those that emerge via exceptions from deep in the YAML parser.

This PR was motivated by Kathy's review ticket feedback, combined with my earlier realization that it was The Right Thing to Do.

**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2105

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that your code compiles by running `npm run build`
- [x] If this is the first time you're submitting a PR or even if you just need a refresher, consider reviewing our [style guide](https://github.com/dockstore/dockstore/wiki/Dockstore-Frontend-Opinionated-Style-Guide#pr-checklist)
- [x] Do not bypass Angular sanitization (bypassSecurityTrustHtml, etc.), or justify why you need to do so
- [x] If displaying markdown, use the `markdown-wrapper` component, which does extra sanitization
- [x] Do not use cookies, although this may change in the future
- [x] Run `npm audit` and ensure you are not introducing new vulnerabilities
- [x] Do due diligence on new 3rd party libraries, checking for CVEs
- [x] Don't allow user-uploaded images to be served from the Dockstore domain

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]
Based on the screenshot, it would be nice if you could indent the children of "In version...".  It doesn't matter for one repo->one workflow, but would be useful for one repo -> many workflows.

But I don't think you can easily tell. And this is much better that what it was. So, it's fine, just brainstorming.

What I mean is, now it's:

```
In version foo of workflow goo
A validation error
In version foo of workflow bar
A validation error
Another validation error
```

to:

```
In version foo of workflow goo
  A validation error
In version foo of workflow bar 
  A validation error
  Another validation error
```

Also see my comment on the web service ticket with a suggestion on the wording.

**Comment by svonworl** [comment]
> Based on the screenshot, it would be nice if you could indent the children of "In version...". It doesn't matter for one repo->one workflow, but would be useful for one repo -> many workflows.
> 
> But I don't think you can easily tell. And this is much better that what it was. So, it's fine, just brainstorming.
> 
> What I mean is, now it's:
> 
> ```
> In version foo of workflow goo
> A validation error
> In version foo of workflow bar
> A validation error
> Another validation error
> ```
> 
> to:
> 
> ```
> In version foo of workflow goo
>   A validation error
> In version foo of workflow bar 
>   A validation error
>   Another validation error
> ```
> 
> Also see my comment on the web service ticket with a suggestion on the wording.

The messages are formatted by the webservice, so we can do the indenting pretty easy (in the other PR).

**Review by kathy-t — APPROVED** [review]

**Review by denis-yuen — APPROVED** [review]
> This PR was motivated by Kathy's review ticket feedback, combined with my earlier realization that it was The Right Thing to Do. 

:grin:

**Review by Richard-Hansen — APPROVED** [review]
The recent changes to GitHub App logs have made them far more actionable, thanks for taking the time to make these upgrades!

**Pull request merged**
