### PR TITLE
Feature/use new launch buttons

### PR DESCRIPTION
**Pull request by Richard-Hansen**
Two minor changes. Ran smoke tests locally and they passed using the new launch with buttons.
1. Switches back to the new launch with buttons
2. Adds names to the dev/staging smoke test jobs that run

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]

**Review by garyluu — APPROVED** [review]

**Review by denis-yuen — APPROVED** [review]

**Review by denis-yuen — COMMENTED** [review]
Hmmm, with the caveat that we're not sure if DNAstack would make it into 1.12 if we do a fast(?) release. Not sure how likely that is

**Review by chmreid — APPROVED** [review]

**Comment by Richard-Hansen** [comment]
> Hmmm, with the caveat that we're not sure if DNAstack would make it into 1.12 if we do a fast(?) release. Not sure how likely that is

Another option is to change the dev smoke tests to match what's in staging, and leave the buttons as-is. Thoughts?

**Comment by coverbeck** [comment]
> Another option is to change the dev smoke tests to match what's in staging, and leave the buttons as-is. Thoughts?

That's probably best. Unfortunately, the property affects all WDL buttons, not just the DNAstack one, I don't think it's worth the effort to change that.

**Comment by Richard-Hansen** [comment]
> > Another option is to change the dev smoke tests to match what's in staging, and leave the buttons as-is. Thoughts?
> 
> That's probably best. Unfortunately, the property affects all WDL buttons, not just the DNAstack one, I don't think it's worth the effort to change that.

Moved the staging and dev tests back into shared, this keeps the old launch with buttons, and the tests run successfully against dev and staging.

**Review by coverbeck — APPROVED** [review]

**Review by denis-yuen — APPROVED** [review]

**Pull request merged**
