### PR TITLE
Fix/3862/public dockerfile download

### PR DESCRIPTION
**Pull request by garyluu**
Basically...use the custom download path no matter what for CONTAINERFILES because there's surprisingly no endpoint that gets the raw text for it

WDL => PLAIN_WDL
CWL => PLAIN_CWL
CONTAINERFILE => ???

For dockstore/dockstore#3862

### CODE REVIEW

**Comment by denis-yuen** [comment]
> Basically...use the custom download path no matter what for CONTAINERFILES because there's surprisingly no endpoint that gets the raw text for it 

:cry:

**Review by denis-yuen — COMMENTED** [review]
Can we determine the path and then grab it from relative files?

**Comment by garyluu** [comment]
> Can we determine the path and then grab it from relative files?


The relative files endpoint requires a type as a path parameter

It's possible, but kind of hacky though because that endpoint requires a type (PLAIN_CWL, PLAIN_WDL, etc)

https://dockstore.org/api/api/ga4gh/v2/tools/quay.io%2Fpancancer%2Fpcawg-sanger-cgp-workflow/versions/2.1.0/PLAIN-WDL/descriptor/Dockerfile

I don't know what will happen if there's no valid CWL or WDL descriptor

**Comment by denis-yuen** [comment]
> I don't know what will happen if there's no valid CWL or WDL descriptor

Long term, we should create a PR to TRS to add raw text containerfiles. 

In the meantime, without a valid CWL or WDL descriptor (if you cannot determine a type), I'd be fine with disabling the link (i.e. keep the current file display, but don't bother with a TRS link)

**Comment by garyluu** [comment]
> > I don't know what will happen if there's no valid CWL or WDL descriptor
> 
> Long term, we should create a PR to TRS to add raw text containerfiles.
> 
> In the meantime, without a valid CWL or WDL descriptor (if you cannot determine a type), I'd be fine with disabling the link (i.e. keep the current file display, but don't bother with a TRS link)

Seems like using the custom download link is a better alternative than disabling the link. But I guess others should weigh in

**Comment by denis-yuen** [comment]
> Seems like using the custom download link is a better alternative than disabling the link. But I guess others should weigh in

Think there is a misunderstanding, I thought you were saying this would be a pain due to 

> I don't know what will happen if there's no valid CWL or WDL descriptor 

But if you're saying that we can use relative TRS when valid descriptors are available and it is simply to use a custom (proprietary) link otherwise than sounds fine to me.

**Comment by garyluu** [comment]
> > Seems like using the custom download link is a better alternative than disabling the link. But I guess others should weigh in
> 
> Think there is a misunderstanding, I thought you were saying this would be a pain due to
> 
> > I don't know what will happen if there's no valid CWL or WDL descriptor
> 
> But if you're saying that we can use relative TRS when valid descriptors are available and it is simply to use a custom (proprietary) link otherwise than sounds fine to me.



> > Seems like using the custom download link is a better alternative than disabling the link. But I guess others should weigh in
> 
> Think there is a misunderstanding, I thought you were saying this would be a pain due to
> 
> > I don't know what will happen if there's no valid CWL or WDL descriptor
> 
> But if you're saying that we can use relative TRS when valid descriptors are available and it is simply to use a custom (proprietary) link otherwise than sounds fine to me.

This is how the conversation/PR went from my POV:
1. I created a PR that uses a custom download link based on contents of the file
2. You asked if relative paths endpoint was possible (won't require custom download link because it's a direct link to the raw text file)
3. I said it's hacky because of "I don't know what will happen if there's no valid CWL or WDL descriptor"
4. You said abandon both solutions and disable the link?

**Comment by denis-yuen** [comment]
Yeah, I think 3 is where the miscommunication starts and 4 is wrong as a result.

**Review by coverbeck — COMMENTED** [review]
Do I have this right? The options are:

1. Always Dockstore API (the PR as is)
2. Use TRS API when possible; use Dockstore API if not possible

What are the

**Comment by garyluu** [comment]
> Do I have this right? The options are:
> 
> 1. Always Dockstore API (the PR as is)
> 2. Use TRS API when possible; use Dockstore API if not possible
> 
> What are the

Options are:
1. Use the TRS /containers endpoint to get the JSON which has the contents of file and then create a custom download link with that content
2. Hackily guess the descriptor type and use the TRS relative paths endpoint as a direct link to download. Multiple fallbacks with extra calls + complexity.
3. Try and dig up the old PR and issue that made this change (something about why the Dockerfile tab has a descriptor type dropdown)

**Comment by denis-yuen** [comment]
I think we can rule out 4, could use more explanation about 3 (what drop down?)

**Comment by garyluu** [comment]
> > Seems like using the custom download link is a better alternative than disabling the link. But I guess others should weigh in
> 
> Think there is a misunderstanding, I thought you were saying this would be a pain due to
> 
> > I don't know what will happen if there's no valid CWL or WDL descriptor
> 
> But if you're saying that we can use relative TRS when valid descriptors are available and it is simply to use a custom (proprietary) link otherwise than sounds fine to me.

The relative files endpoint requires a type as a path parameter

It's possible, but kind of hacky though because that endpoint requires a type (PLAIN_CWL, PLAIN_WDL, etc)

> I think we can rule out 4, could use more explanation about 3 (what drop down?)

You know how in the Descriptor Files tab, there's a Descriptor Type dropdown where you can choose between CWL and WDL.  We used to have that in the Dockerfile tab, but I think someone on our team said it didn't make sense so it was removed.

**Comment by denis-yuen** [comment]
Oh I see, as in we had a drop-down at some point but we do not now. Thanks

**Review by denis-yuen — APPROVED** [review]
To clarify current situation:

1. Current deploy has a broken link (or rather a link to json content) on TRS
2. This PR would create a custom download link, which isn't TRS but is functional 
3. It seems like using TRS would either be difficult or require TRS changes

If this is true, I'm ok with this for now as long as you open a new TRS ticket to make it easier to get TRS dockerfile content

**Review by coverbeck — APPROVED** [review]

**Review by wshands — APPROVED** [review]

**Comment by garyluu** [comment]
18 days elapsed, merging

**Pull request merged**
