### PR TITLE
Changed the ORCID logo size

### PR DESCRIPTION
**Pull request by e34lin**
The logo size is now 16x16 instead of 14x14

### CODE REVIEW

**Comment by denis-yuen** [comment]
Can we get this to the `release/2.8` branch as well?

**Review by garyluu — COMMENTED** [review]
There's also a

```
img.site-icons-small {
  width: 16px;
  height: 16px;
}
```

I recently noticed. Others should weigh in but I think that's more generic and re-usable for setting icon width than this orcid-id-logo. Going to need to retain this class for the `vertical-align: sub` though

**Review by denis-yuen — APPROVED** [review]
With Gary's change for develop

**Review by coverbeck — COMMENTED** [review]
I think you can close this, as it will get merged via your other PR and the Hubflow/hotfix process.

**Comment by coverbeck** [comment]
> I think you can close this, as it will get merged via your other PR and the Hubflow/hotfix process.

Or am I wrong, and you're going to do it differently based on Gary's comment.

**Comment by e34lin** [comment]
> > I think you can close this, as it will get merged via your other PR and the Hubflow/hotfix process.
> 
> Or am I wrong, and you're going to do it differently based on Gary's comment.

Yeah, I am going to do it differently based on Gary's comment.

**Review by garyluu — APPROVED** [review]

**Review by denis-yuen — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]

**Review by kathy-t — APPROVED** [review]

**Pull request merged**
